--SELECT * FROM SH.CUSTOMERS; для удобства
--SELECT * FROM SH.COUNTRIES;
--SELECT * FROM SH.PRODUCTS;
--SELECT * FROM ALEXPERCH_SALES;
--SELECT * FROM SALES_USER5_ALEX_PERCH;

--№1
--Так как в задании не указанно какой долежен быть CUST_CREDIT_LIMIT у бедного клиента, а какой у богатого
--я посмотрел в таблицу и решил что бедным клиентам будет любой клиент с CUST_CREDIT_LIMIT <= 3000

SELECT CUST_FIRST_NAME, CUST_LAST_NAME FROM SH.CUSTOMERS JOIN SH.COUNTRIES USING(COUNTRY_ID) 
WHERE SH.COUNTRIES.COUNTRY_NAME NOT IN ('Japan', 'Brazil', 'Italy') 
AND SH.CUSTOMERS.CUST_GENDER = 'F'  
AND SH.CUSTOMERS.CUST_MARITAL_STATUS = 'married' 
AND SH.CUSTOMERS.CUST_CREDIT_LIMIT <= 3000;

--№2

SELECT 'Name: ' || CUST_FIRST_NAME ||' '|| CUST_LAST_NAME ||' | City: ' || CUST_CITY || ' | Address ' || 
CUST_STREET_ADDRESS || ' | Number '|| CUST_MAIN_PHONE_NUMBER ||' | Email: ' || CUST_EMAIL 
AS "INFORMATION_ABOUT_CLIENT" FROM SH.CUSTOMERS
WHERE LENGTH(CUST_STREET_ADDRESS) = ( SELECT MAX(LENGTH(CUST_STREET_ADDRESS)) FROM SH.CUSTOMERS WHERE CUST_MAIN_PHONE_NUMBER LIKE '%77');

--№3

SELECT CUST_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_YEAR_OF_BIRTH, PROD_CATEGORY 
FROM SH.CUSTOMERS JOIN SH.SALES  USING(CUST_ID) JOIN SH.PRODUCTS USING(PROD_ID)
WHERE CUST_YEAR_OF_BIRTH > 1980 
AND PROD_LIST_PRICE = (SELECT MIN(PROD_LIST_PRICE) FROM SH.PRODUCTS WHERE PROD_CATEGORY IN ('Girls', 'Women'));

--№4

SELECT * FROM SH.CUSTOMERS
WHERE CUST_GENDER = 'M' AND CUST_INCOME_LEVEL LIKE 'D%' AND CUST_MARITAL_STATUS IS NULL AND
EXISTS (SELECT COUNTRY_ID FROM SH.COUNTRIES 
WHERE COUNTRY_NAME IN ('Germany', 'United States of America')
AND SH.COUNTRIES.COUNTRY_ID = SH.CUSTOMERS.COUNTRY_ID);

--№5
--Создал новый столбец ALL_SOLD, так как неизвестно по какому столбцу считать и сортировать

SELECT COUNTRY_NAME, AVG(ALL_SOLD) FROM SH.COUNTRIES JOIN SH.CUSTOMERS USING(COUNTRY_ID) JOIN SH.SALES USING(CUST_ID)
GROUP BY COUNTRY_NAME ORDER BY AVG(ALL_SOLD) DESC;

--№6
--Честно скажу, не понимаю что требуется, даже мыслей нет
--а понял, не сразу заметил что домены разные есть

SELECT DOMAIN, COUNT(*) AS "DOMAIN_COUNT"
FROM (SELECT SUBSTR(CUST_EMAIL,INSTR(CUST_EMAIL,'@')) AS "DOMAIN" FROM SH.CUSTOMERS)
GROUP BY DOMAIN;

--№7,8,9,10,

--СЛОЖНО

--№11

CREATE VIEW ALEXPERCH_SALES AS (SELECT TRUNC(TIME_ID,'MM') AS MONTH, COUNT(*) AS "SALES_COUNT"
FROM SH.SALES GROUP BY TRUNC(TIME_ID,'MM'));

CREATE TABLE SALES_USER5_ALEX_PERCH AS (SELECT * FROM SH.SALES
WHERE TRUNC(TIME_ID,'MM') = (SELECT MIN(MONTH) FROM ALEXPERCH_SALES
WHERE SALES_COUNT = (SELECT MAX(SALES_COUNT) FROM ALEXPERCH_SALES)));

--№12

ALTER TABLE SALES_USER5_ALEX_PERCH
ADD (TIME_ID_NEW CHAR(19));

UPDATE SALES_USER5_ALEX_PERCH
SET TIME_ID_NEW = TO_CHAR (TIME_ID + NUMTODSINTERVAL(MOD(ABS(DBMS_RANDOM.RANDOM),24 * 60 * 60),'second'),'DD.MM.YYYY HH:MI:SS');

ALTER TABLE SALES_USER5_ALEX_PERCH
DROP COLUMN TIME_ID;

ALTER TABLE SALES_USER5_ALEX_PERCH
RENAME COLUMN TIME_ID_NEW TO TIME_ID;

--№13

SELECT HOUR, SUM(QUANTITY_SOLD) AS "QUANITITY_SOLD_ALEXPERCH"
FROM (SELECT SUBSTR(TIME_ID,1,13) AS HOUR, QUANTITY_SOLD FROM SALES_USER5_ALEX_PERCH)
GROUP BY HOUR;

--№14

DROP TABLE SALES_USER5_ALEX_PERCH;